### ISSUE TITLE
ESP32 port

### ISSUE THREAD

**Issue by kd8bxp** [DrZingo/c64-wifimodem#1]
Hi, I just wanted to let you know that I ported the code over to a ESP32 - using a TTGO T-Eight board with OLED (there are at least two different boards called T-Eight from TTGO/LilyGo so depending on which board you have you might need to change/update the OLED pin numbers)
Mostly the code was easy to port and use - I ran into a issue with the telnet server - and it's not working, I'm not real sure how to make that work.
But if you are or anyone is interested in using a ESP32 - this might be a good place to started and fix my port :-) 
https://github.com/kd8bxp/c64-wifimodem/tree/esp32
Also, I'm using this to get my Tandy 102 on WiFi, and I think it will also work with my Apple IIc, but I'll have to make a cable for that.
I am planning on making a edge connector to 9 pin serial so I can also use this with my C64. :-) 
![2019-05-22 23 14 40](https://user-images.githubusercontent.com/7252172/58606475-8d946380-8269-11e9-9c60-3c846734f279.jpg)

**Comment by DrZingo** [comment]
Great!
I hope you get some help with your port. I have no possibility to test myself, and therefore I will not merge it into my repo. Thanks anyway, always great to see the retro scene thrive. :)

**Comment by kd8bxp** [comment]
No problem, I understand - I hope someone can help, I'd like to get telnet working. Have a great day, and thanks for original code, and inspiration to build mine.
